### ISSUE TITLE
Combine Message board with Time.h

### ISSUE THREAD

**Issue by Ukhauk** [G6EJD/ESP8266-Remote-Message-Board#1]
Hi thanks for posting your projects love this message board. I was thinking could you combine this project with the Time.h video so that the Day,Date,Time is displayed until a message comes in on the web page ? perhaps a parameter in the message could tell the display how many times to display the received message ?

Also using the WiFiManager.h could this contain the NTP provider looks like this library allows additional info might be handy so it can be changed without using the Adriano ide ?

I have been using nodered to send messages to the display ? might be worth a video ?

I made this mod to your message board so that the display IP address comes up as the first message when it boots handy if IP address is not fixed. 

  String IPaddress = WiFi.localIP().toString();
  message = "WiFi connected... "+ IPaddress; //"Message Board (C) D.L.Bird 2017";
  display_message(message); // Display the message
  wait    = 75;
  message = "Welcome ...";

**Comment by G6EJD** [comment]
Well it could be if the ESP8266 compiler would allow correct time implementation, but it does not AFAIK. For sure the DST option does not work and formatting time is very difficult, no where enar that possible for the ESP32. There is no further development of the ESP8266 development environment, although this issue may have been fixed in the forthcoming 2.4 rc of the Arduino IDE ESP update due soon.

You can display a fixed format time relatively easily like this:

void SetupTime(){ 
   configTime(1 * 3600, 0, "pool.ntp.org", "time.nist.gov"); 
   Serial.println("\nWaiting for time"); 
   while (!time(nullptr)) { 
     delay(500); 
   } 
 } 

Then when you need time do this:
time_t now = time(nullptr);  time_str = ctime(&now).toString();

Then add a new variable called say 'default_message' and assign it time
default_message = time_str;
if (message == "") {
   message = default_message; 
} 

Then if nothing is received into message from the command line of the browser message = "" so the default message is display which will be time.

**Comment by Ukhauk** [comment]
To be honest I hadn't noticed your Tech Note was based on the ESP32 ! Dooh all is clear now. Thanks for taking the time to do the youtube video's and your code suggestions which i'm happy to say mostly got working. Just looking now for  a decent way to package the display now like the acrylic tube examples.

**Comment by G6EJD** [comment]
Getting time on the ESP8266 is a little tricky, now easier on the ESP32.  You can get a full time string OK on the ESP8266. I've found getting a Perspex colour that suits my RED led display quite difficult, in the end I went for a grey colour, I think it was called smoke-grey and that gives a good compromise between letting light out and not being able to see the display board/inners. 

This is usually the problematic statement: time_str = ctime(&now).toString(); and converting the Char array to string for easier manipulation. If you have not solved this; sometimes it crashes or returns null, then let me know as I have a solution somewhere.

**Comment by G6EJD** [comment]
With the ESP core 2.4.1 in the IDE time services are now working.

**Comment by suryatej9988** [comment]
Can you please tell how you created the message board v1.0.

**Comment by G6EJD** [comment]
I use the Arduino IDE with ESP extension.
